### ISSUE TITLE
Unable to deploy any contract on Vide inside Sync v1.1.0

### ISSUE THREAD

**Issue by shaurya-ObjC** [mobileteamdev/vide-web#2]
I am trying to deploy a small contract which was working perfectly on version 1.0.0, however when my Vechain sync updated to version 1.1.0 automatically, I am unable to deploy any contract on same. When I tap on deploy contract it simply shows me nothing. Even it doesn't opens a window for selecting any of the test account. So, I am unable to pay any vetho.

CODE what I am trying to deploy with compiler version: 0.4.24+commit.e67f0147.Emscripten.clang

pragma solidity ^0.4.24;

contract message {
int myMessage;

function setValue(int x) public {
    myMessage = x;
}

function getValue() public view returns (int) {
    return myMessage;
}
}

Current Output:- Nothing
And in console I see this only "creation of message pending..."

Expected Output:- Should return the address of contract where it's deployed.

Versions:-
MacOS 10.13.6.
Sync - v1.1.0
Connex: 1.4.0
Electron: 3.0.16
Chrome: 66.0.3359.181
V8: 6.6.346.32

**Comment by mobileteamdev** [comment]
@shaurya-ObjC Probably the problem of cache on Sync, I created a new path, you should try https://vechainstore.com/ide/connex1.4.0

**Comment by shaurya-ObjC** [comment]
@mobileteamdev When I open above link inside Sync, it displays me error "Failed to Open". 
I even reinstalled the sync version 1.1.0.
<img width="416" alt="Screen Shot 2019-09-05 at 10 02 09 AM" src="https://user-images.githubusercontent.com/3593159/64317847-65d63980-cfd6-11e9-93c8-1d5f646e498a.png">

**Comment by XJWX89** [comment]
> @mobileteamdev When I open above link inside Sync, it displays me error "Failed to Open".
> I even reinstalled the sync version 1.1.0.
> <img alt="Screen Shot 2019-09-05 at 10 02 09 AM" width="416" src="https://user-images.githubusercontent.com/3593159/64317847-65d63980-cfd6-11e9-93c8-1d5f646e498a.png">

After investigation, we found out that there are two different type of content-encoding(`br` & `gzip`). @mobileteamdev  can you change the encoding back to gzip ?

**Comment by mobileteamdev** [comment]
@shaurya-ObjC , @XJWX89  I have updated Content-Encoding: gzip, if you can not clear the cache on Sync then visit this link https://vechainstore.com/ide/connex1.4.0/index.php

**Comment by XJWX89** [comment]
hi @mobileteamdev , it seems there are 3 files still in `br` encoding. please check below files
1.  app.js
2.  pygment_trac.css 
3. font-awesome.min.css 0 ()

**Comment by shaurya-ObjC** [comment]
@mobileteamdev 

After clearing all caches from ~/Library/Caches, even from  ~/Library/Application Support/org.vechain.sync/ as well.

I tried with this link, https://vechainstore.com/ide/connex1.4.0/index.php. It's displaying me white blank page.
And other links are showing me the previous errors i.e. "Failed to Open".

**Comment by mobileteamdev** [comment]
@shaurya-ObjC I visit the website (from Vietnam) completely normal, I contacted the hosting provider to ask them to check, you can try again on Sync and Chrome, if there's still an error please let me know, thank you!

**Comment by shaurya-ObjC** [comment]
@mobileteamdev It's working fine. Now I am able to deploy the contract.
I tested for https://vechainstore.com/ide/connex1.4.0/index.php and https://vechainstore.com/ide on Sync v 1.1.0 

Thanks for solving.
